name: Transaction
description: Deposit, redeem, or set the Vault balance
title: "[Transaction] "
labels: ["transactions"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Transaction Type
      options:
        - deposit
        - redeem
        - set
    validations:
      required: true

  - type: input
    id: amount
    attributes:
      label: Amount (VP)
      placeholder: e.g., 10
    validations:
      required: true

  - type: input
    id: player
    attributes:
      label: Player
      description: Leave blank to use the default player from settings.yaml
      placeholder: e.g., default
    validations:
      required: false

  - type: input
    id: description
    attributes:
      label: Description
      placeholder: e.g., Daily deposit - Monday
    validations:
      required: true
